[classifications]
Internet = ["Telefonica Germany GmbH + Co. OHG"]
Nettogehalt = []
Kindergeld = []
Zuschuesse = []
Miete = []
Strom = []
Haftpflicht = []
Hausrat = []
BU = []
SonstigeVersicherungen = []
ETF_Sparplaene = []
Sonstige_Sparplaene = []
Lebensversicherung = []
Kreditrate = []
Leasing = []
Bankarte = []
Handy = []
Streaming = []
Rundfunk = []
SonstigeVertraege = []
Lebensmittel = []
Kleidung = []
Sonstige_Lebenserhaltung = []
Tanken = []
Ausgehen = []
Geschenke = []
Spenden = []
Sonstige = []

